name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 현재 작업 디렉토리(_work/ITDA-front)에 바로 코드를 받습니다.
          path: "."

      - name: Execute Deploy Script
        run: |
          chmod +x ~/deploy_frontend.sh
          ~/deploy_frontend.sh
